STORE_PRODUCTS = [
    {
        "id": 1,
        "sku": "WH-001",
        "name": "Wireless Headphones",
        "category": "Electronics",
        "query": "wireless headphones",
        "currentPrice": 89.99,
        "supplierCost": 55.00,
        "minPrice": 79.99,
        "maxPrice": 119.99,
    },
    {
        "id": 2,
        "sku": "SW-001",
        "name": "Smart Watch",
        "category": "Electronics",
        "query": "smart watch",
        "currentPrice": 299.99,
        "supplierCost": 210.00,
        "minPrice": 249.99,
        "maxPrice": 349.99,
    },
    {
        "id": 3,
        "sku": "USB-001",
        "name": "USB-C Cable 6ft",
        "category": "Electronics",
        "query": "usb c cable 6ft",
        "currentPrice": 12.99,
        "supplierCost": 5.00,
        "minPrice": 9.99,
        "maxPrice": 19.99,
    },
]